// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjxwlrhxirglcmifwgyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqeHdscmh4aXJnbGNtaWZ3Z3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTIzMjMsImV4cCI6MjA1OTY4ODMyM30.TiGxcakJg3QHI_LMw8RR4nIJALQu75uqF6TOa5_vxK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);